name: Conventional Commit Validation

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:
      - [ main, master ]

jobs:
  build:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: validate Conventional Commits
        uses: webiny/action-conventional-commits@v1.3.0
        with:
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Optional, for private repositories.
          allowed-commit-types: "feat,fix,docs,style,refactor,perf,test,ci,chore,build,revert"

      - name: Validate semantic versioning
        uses: matt-usurp/validate-semver@v2
        with:
          version: 1.0.0

      - name: Send Email upon failures
        if: ${{ failure() }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.ethereal.com
          server_port: 587
          username: ${{ secrets.ETHEREAL_USERNAME }}
          password: ${{ secrets.ETHEREAL_PASSWORD }}
          subject: "Github Action Failure: Conventional commit check failed <No Reply>."
          body: |
            Commit messages do not follow the conventional commit format or semantic versioning is invalid.
            Please fix them before pushing or pull request.
          to: "likhithabz55@gmail.com"
          from: "${{ secrets.ETHEREAL_USERNAME }}"
