name: Nightly Build

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      #- name: Setup .env
        #run: |
        #  cp .env.example .env
        #  echo ".env created"

      - name: Build docker images
        run: docker compose build

      - name: Start Services
        run: docker compose up -d

      - name: Run tests in web container
        run: docker compose exec web pytest

      - name: Stop and Remove Containers
        run: docker compose down -v

      - name: Log in to GitHub Container Registry
        if: success()
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        if: success()
        uses: docker/build-push-action@v6
        with:
          push: 'true'
          tags: ghcr.io/${{ github.actor }}/fastapi-beyond-crud:nightly

      - name: Send email upon failure
        if: ${{ failure() }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.ethereal.email
          server_port: 587
          username: ${{ secrets.ETHEREAL_USERNAME }}
          password: ${{ secrets.ETHEREAL_PASSWORD }}
          subject: "Github Action Failure: Nightly build failed <No Reply>"
          body: |
            Nightly build failed due to issues in build or tests.
            Image not pushed to registry.
          to: "likhithabz55@gmail.com"
          from: "${{ secrets.ETHEREAL_USERNAME }}"


          

            
        
